/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gshx_camera_tiandi_NativeTiandi */

#ifndef _Included_com_gshx_camera_tiandi_NativeTiandi
#define _Included_com_gshx_camera_tiandi_NativeTiandi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gshx_camera_tiandi_NativeTiandi
 * Method:    nativeCreateInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gshx_camera_tiandi_NativeTiandi_nativeCreateInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_gshx_camera_tiandi_NativeTiandi
 * Method:    nativeDestroyInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gshx_camera_tiandi_NativeTiandi_nativeDestroyInstance
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
